server:
  port: 8080

spring:
  application:
    name: order-service

  # database config
  datasource:
    url: jdbc:postgresql://localhost:5432/${ORDER_SERVICE_DB_NAME}
    username: ${ORDER_SERVICE_DB_USERNAME}
    password: ${ORDER_SERVICE_DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgresPlusDialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true


# resilience4j config
resilience4j:
  retry:
    instances:
      inventoryRetry:
        max-attempts: 3
        wait-duration: 1s
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - org.springframework.web.client.RestClientException
          - java.io.IOException
        ignore-exceptions:
          # Fixed: Inner classes use '$' instead of '.' in YAML exception lists
          - org.springframework.web.client.HttpClientErrorException$TooManyRequests
          - io.github.resilience4j.ratelimiter.RequestNotPermitted
  ratelimiter:
    configs:
      default:
        limit-refresh-period: 10s
        timeout-duration: 0s
        # Moved here because both instances share the same limit
        limit-for-period: 5
        register-health-indicator: true
        subscribe-for-events: true
    instances:
      inboundLimiter:
        base-config: default
      outboundLimiter:
        base-config: default


# eureka config
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

# 4. Open up endpoints to check if limits are active
management:
  endpoints:
    web:
      exposure:
        include: health, info, ratelimiters
  endpoint:
    health:
      show-details: always

# microservices config
services:
    inventory:
      base-url: "http://INVENTORY-SERVICE"
      connection-timeout: 5s
      read-timeout: 5s

