server:
  port: 8080

spring:
  application:
    name: order-service

  # database config
  datasource:
    url: jdbc:postgresql://localhost:5432/${ORDER_SERVICE_DB_NAME}
    username: ${ORDER_SERVICE_DB_USERNAME}
    password: ${ORDER_SERVICE_DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgresPlusDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true


# resilience4j config
resilience4j:
  retry:
    instances:
      inventoryRetry:
        maxAttempts: 3
        waitDuration: 1s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        retryExceptions:
          - org.springframework.web.client.RestClientException
          - java.io.IOException


# eureka config
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

# microservices config
services:
    inventory:
      base-url: "http://INVENTORY-SERVICE"
      connection-timeout: 5s
      read-timeout: 5s

