spring:
  application:
    name: product-service
  mongodb:
    host: localhost
    port: 27017
    database: ${PRODUCT_SERVICE_DB_NAME}
    username: ${PRODUCT_SERVICE_DB_USERNAME}
    password: ${PRODUCT_SERVICE_DB_PASSWORD}
    authentication-database: admin

server:
  port: 8082

